# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import UTC
from datetime import datetime
from uuid import uuid4

from freezegun import freeze_time

from mo_smtp.autogenerated_graphql_client.manager_data import (
    ManagerDataManagersObjectsValidities,
)
from mo_smtp.helpers import extract_current_or_latest_validity
from mo_smtp.helpers import next_send_time


def _validity(from_: str, to: str | None) -> ManagerDataManagersObjectsValidities:
    return ManagerDataManagersObjectsValidities.parse_obj(
        {
            "validity": {
                "from": datetime.fromisoformat(from_).replace(tzinfo=UTC),
                "to": datetime.fromisoformat(to).replace(tzinfo=UTC) if to else None,
            },
            "org_unit_uuid": uuid4(),
        }
    )


@freeze_time("2022-08-10")
def test_returns_the_validity_current_today():
    past = _validity("2022-08-01", "2022-08-02")
    current = _validity("2022-08-05", None)
    assert extract_current_or_latest_validity([past, current]) is current


@freeze_time("2022-08-10")
def test_returns_latest_when_none_current_today():
    older = _validity("2022-08-01", "2022-08-02")
    latest = _validity("2022-08-15", "2022-08-20")
    assert extract_current_or_latest_validity([older, latest]) is latest


def test_returns_none_when_empty():
    assert extract_current_or_latest_validity([]) is None


def test_within_a_ticks_minute_is_send_time():
    # A tick lasts its whole minute: 00:00:30 falls within the 00:00 tick.
    assert next_send_time("0 0 * * *", datetime(2026, 1, 1, 0, 0, 30)) is None


def test_outside_send_time_returns_next_tick():
    # Daily tick at 00:00; at 00:01 the tick's minute has passed, so defer to
    # the next midnight.
    outside = next_send_time("0 0 * * *", datetime(2026, 1, 1, 0, 1))
    assert outside == datetime(2026, 1, 2, 0, 0)


def test_weekly_schedule_within_ticks_minute():
    # Every Thursday at 04:30 — 2026-01-01 is a Thursday.
    assert next_send_time("30 4 * * 4", datetime(2026, 1, 1, 4, 30, 59)) is None


def test_weekly_schedule_defers_to_next_thursday():
    # Every Thursday at 04:30; on Friday the event is deferred a whole week,
    # not to the next day.
    outside = next_send_time("30 4 * * 4", datetime(2026, 1, 2, 10, 0))
    assert outside == datetime(2026, 1, 8, 4, 30)


def test_batch_stays_due_while_draining():
    # An event deferred to the 00:00 tick and redelivered at 00:14 — after the
    # tick's minute, e.g. behind hundreds of others — is still due: its target
    # falls within the current send cycle.
    draining = next_send_time(
        "0 0 * * *",
        datetime(2026, 1, 1, 0, 14, 37),
        not_before=datetime(2026, 1, 1, 0, 0),
    )
    assert draining is None


def test_stale_not_before_is_deferred_to_the_next_tick():
    # An event deferred to YESTERDAY's tick but only delivered today missed its
    # cycle; it is re-deferred to the next tick rather than sent off-schedule.
    stale = next_send_time(
        "0 0 * * *",
        datetime(2026, 1, 2, 10, 0),
        not_before=datetime(2026, 1, 1, 0, 0),
    )
    assert stale == datetime(2026, 1, 3, 0, 0)
