# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import UTC
from datetime import datetime
from uuid import uuid4

from freezegun import freeze_time

from mo_smtp.autogenerated_graphql_client.ituser_validities import (
    ItuserValiditiesItusersObjectsValiditiesItsystemResponse,
)
from mo_smtp.autogenerated_graphql_client.ituser_validities import (
    ItuserValiditiesItusersObjectsValiditiesItsystemResponseValidities,
)
from mo_smtp.autogenerated_graphql_client.manager_data import (
    ManagerDataManagersObjectsValidities,
)
from mo_smtp.helpers import extract_current_or_latest_validity
from mo_smtp.helpers import itsystem_name


def _validity(from_: str, to: str | None) -> ManagerDataManagersObjectsValidities:
    return ManagerDataManagersObjectsValidities.parse_obj(
        {
            "validity": {
                "from": datetime.fromisoformat(from_).replace(tzinfo=UTC),
                "to": datetime.fromisoformat(to).replace(tzinfo=UTC) if to else None,
            },
            "org_unit_uuid": uuid4(),
        }
    )


@freeze_time("2022-08-10")
def test_returns_the_validity_current_today():
    past = _validity("2022-08-01", "2022-08-02")
    current = _validity("2022-08-05", None)
    assert extract_current_or_latest_validity([past, current]) is current


@freeze_time("2022-08-10")
def test_returns_latest_when_none_current_today():
    older = _validity("2022-08-01", "2022-08-02")
    latest = _validity("2022-08-15", "2022-08-20")
    assert extract_current_or_latest_validity([older, latest]) is latest


def test_returns_none_when_empty():
    assert extract_current_or_latest_validity([]) is None


def _itsystem_validity(
    name: str, from_: str | None, to: str | None
) -> ItuserValiditiesItusersObjectsValiditiesItsystemResponseValidities:
    return ItuserValiditiesItusersObjectsValiditiesItsystemResponseValidities.parse_obj(
        {
            "name": name,
            "validity": {
                "from": datetime.fromisoformat(from_).replace(tzinfo=UTC)
                if from_
                else None,
                "to": datetime.fromisoformat(to).replace(tzinfo=UTC) if to else None,
            },
        }
    )


def _itsystem(
    *validities: ItuserValiditiesItusersObjectsValiditiesItsystemResponseValidities,
) -> ItuserValiditiesItusersObjectsValiditiesItsystemResponse:
    return ItuserValiditiesItusersObjectsValiditiesItsystemResponse(
        uuid=uuid4(), validities=list(validities)
    )


@freeze_time("2026-01-01")
def test_names_the_only_validity_even_undated():
    undated = _itsystem_validity("AD", None, None)
    assert itsystem_name(_itsystem(undated)) == "AD"


@freeze_time("2026-01-01")
def test_names_the_period_covering_today():
    current = _itsystem_validity("AD", "1930-01-01", "2030-01-01")
    dated_ahead = _itsystem_validity("Renamed", "2030-01-01", None)
    assert itsystem_name(_itsystem(current, dated_ahead)) == "AD"


@freeze_time("2026-01-01")
def test_names_the_open_period_once_it_has_started():
    past = _itsystem_validity("AD", "1930-01-01", "2020-01-01")
    current = _itsystem_validity("Renamed", "2020-01-01", None)
    assert itsystem_name(_itsystem(past, current)) == "Renamed"


@freeze_time("2026-01-01")
def test_names_the_last_period_to_end_when_terminated():
    older = _itsystem_validity("AD", "1930-01-01", "2020-01-01")
    latest = _itsystem_validity("Last", "2020-01-01", "2023-01-01")
    assert itsystem_name(_itsystem(older, latest)) == "Last"
