# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import UTC
from datetime import datetime
from uuid import uuid4

from freezegun import freeze_time

from mo_smtp.autogenerated_graphql_client.manager_data import (
    ManagerDataManagersObjectsValidities,
)
from mo_smtp.helpers import extract_current_or_latest_validity


def _validity(from_: str, to: str | None) -> ManagerDataManagersObjectsValidities:
    return ManagerDataManagersObjectsValidities.parse_obj(
        {
            "validity": {
                "from": datetime.fromisoformat(from_).replace(tzinfo=UTC),
                "to": datetime.fromisoformat(to).replace(tzinfo=UTC) if to else None,
            },
            "org_unit_uuid": uuid4(),
        }
    )


@freeze_time("2022-08-10")
def test_returns_the_validity_current_today():
    past = _validity("2022-08-01", "2022-08-02")
    current = _validity("2022-08-05", None)
    assert extract_current_or_latest_validity([past, current]) is current


@freeze_time("2022-08-10")
def test_returns_latest_when_none_current_today():
    older = _validity("2022-08-01", "2022-08-02")
    latest = _validity("2022-08-15", "2022-08-20")
    assert extract_current_or_latest_validity([older, latest]) is latest


def test_returns_none_when_empty():
    assert extract_current_or_latest_validity([]) is None
