# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from datetime import timezone
from uuid import UUID

import pytest

from mo_smtp.autogenerated_graphql_client import ClassCreateInput
from mo_smtp.autogenerated_graphql_client import FacetCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import ITSystemCreateInput
from mo_smtp.autogenerated_graphql_client import ITUserCreateInput
from mo_smtp.autogenerated_graphql_client import ManagerCreateInput
from mo_smtp.autogenerated_graphql_client import OrganisationCreate
from mo_smtp.autogenerated_graphql_client import OrganisationUnitCreateInput
from mo_smtp.autogenerated_graphql_client import RAOpenValidityInput
from mo_smtp.autogenerated_graphql_client import RAValidityInput
from mo_smtp.autogenerated_graphql_client import RoleBindingCreateInput
from mo_smtp.autogenerated_graphql_client import ValidityInput

SEED_FROM = datetime(1930, 1, 1, tzinfo=timezone.utc)
SEED_VALIDITY = ValidityInput(from_=SEED_FROM)
SEED_RA_VALIDITY = RAValidityInput(from_=SEED_FROM)
SEED_OPEN_VALIDITY = RAOpenValidityInput(from_=SEED_FROM)


# --- Root org ---


@pytest.fixture
async def root_org(graphql_client: GraphQLClient) -> UUID:
    """Ensure the root organisation exists."""
    r = await graphql_client._testing__create_org_root(
        input=OrganisationCreate(municipality_code=None)
    )
    return r.uuid


# --- Facet fixtures ---


async def _create_facet(graphql_client: GraphQLClient, user_key: str) -> UUID:
    r = await graphql_client._testing__create_facet(
        input=FacetCreateInput(user_key=user_key, validity=SEED_VALIDITY)
    )
    return r.uuid


@pytest.fixture
async def employee_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "employee_address_type")


@pytest.fixture
async def org_unit_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "org_unit_address_type")


@pytest.fixture
async def org_unit_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_type")


@pytest.fixture
async def engagement_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "engagement_type")


@pytest.fixture
async def engagement_job_function_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "engagement_job_function")


@pytest.fixture
async def role_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "role")


@pytest.fixture
async def manager_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_type")


@pytest.fixture
async def manager_level_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_level")


@pytest.fixture
async def responsibility_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "responsibility")


# --- Class fixtures ---


async def _create_class(
    graphql_client: GraphQLClient,
    facet_uuid: UUID,
    user_key: str,
    name: str,
    scope: str | None = None,
) -> UUID:
    r = await graphql_client._testing__create_class(
        input=ClassCreateInput(
            user_key=user_key,
            name=name,
            facet_uuid=facet_uuid,
            scope=scope,
            validity=SEED_VALIDITY,
        )
    )
    return r.uuid


@pytest.fixture
async def email_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "EmailEmployee", "Email", "EMAIL"
    )


@pytest.fixture
async def phone_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "PhoneEmployee", "Telefon", "PHONE"
    )


@pytest.fixture
async def email_unit(
    graphql_client: GraphQLClient, org_unit_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, org_unit_address_type_facet, "EmailUnit", "Email", "EMAIL"
    )


@pytest.fixture
async def afdeling(graphql_client: GraphQLClient, org_unit_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, org_unit_type_facet, "Afdeling", "Afdeling"
    )


@pytest.fixture
async def ansat(graphql_client: GraphQLClient, engagement_type_facet: UUID) -> UUID:
    return await _create_class(graphql_client, engagement_type_facet, "Ansat", "Ansat")


@pytest.fixture
async def jurist(
    graphql_client: GraphQLClient, engagement_job_function_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, engagement_job_function_facet, "Jurist", "Jurist"
    )


@pytest.fixture
async def niveau1(graphql_client: GraphQLClient, manager_level_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, manager_level_facet, "Niveau1", "Niveau 1"
    )


@pytest.fixture
async def direktoer(graphql_client: GraphQLClient, manager_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, manager_type_facet, "Direktoer", "Direktør"
    )


@pytest.fixture
async def ansvar(graphql_client: GraphQLClient, responsibility_facet: UUID) -> UUID:
    return await _create_class(graphql_client, responsibility_facet, "Ansvar", "Ansvar")


@pytest.fixture
async def rolle(graphql_client: GraphQLClient, role_facet: UUID) -> UUID:
    return await _create_class(graphql_client, role_facet, "Rolle", "Rolle")


@pytest.fixture
async def active_directory(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    """An 'Active Directory' IT system to hang IT-users on."""
    r = await graphql_client._testing__create_i_t_system(
        input=ITSystemCreateInput(
            user_key="Active Directory",
            name="Active Directory",
            validity=SEED_OPEN_VALIDITY,
        )
    )
    return r.uuid


# --- Object factory fixtures ---
#
# Only objects whose MO-required fields are irrelevant to the tests live here
# (org units hide `org_unit_type`; managers hide level/type/responsibility;
# IT-users/rolebindings hide validity), so tests read as e.g.
# `create_manager(person=..., org_unit=...)` without the noise. Objects whose
# fields *are* the data under test (employees, addresses) are created inline in
# the tests instead.


@pytest.fixture
async def create_org_unit(
    graphql_client: GraphQLClient, afdeling: UUID
) -> Callable[..., Awaitable[UUID]]:
    """Return a callable that creates an org unit.

    `user_key` defaults to the object UUID in MO; pass it explicitly when a test
    needs to assert against it.
    """

    async def inner(
        name: str,
        user_key: str | None = None,
        parent: UUID | None = None,
    ) -> UUID:
        r = await graphql_client._testing__create_org_unit(
            input=OrganisationUnitCreateInput(
                name=name,
                user_key=user_key,
                parent=parent,
                org_unit_type=afdeling,
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
async def create_manager(
    graphql_client: GraphQLClient,
    niveau1: UUID,
    direktoer: UUID,
    ansvar: UUID,
) -> Callable[..., Awaitable[UUID]]:
    """Return a callable that makes a person manager of an org unit.

    Pass `person=None` to create a vacant manager role.
    """

    async def inner(person: UUID | None, org_unit: UUID) -> UUID:
        r = await graphql_client._testing__create_manager(
            input=ManagerCreateInput(
                person=person,
                org_unit=org_unit,
                manager_level=niveau1,
                manager_type=direktoer,
                responsibility=[ansvar],
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def create_ituser(
    graphql_client: GraphQLClient,
) -> Callable[..., Awaitable[UUID]]:
    """Return a callable that creates an IT user on an IT system for a person."""

    async def inner(user_key: str, itsystem: UUID, person: UUID) -> UUID:
        r = await graphql_client._testing__create_i_t_user(
            input=ITUserCreateInput(
                user_key=user_key,
                itsystem=itsystem,
                person=person,
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def create_rolebinding(
    graphql_client: GraphQLClient,
) -> Callable[..., Awaitable[UUID]]:
    """Return a callable that binds a role to an IT user."""

    async def inner(ituser: UUID, role: UUID) -> UUID:
        r = await graphql_client._testing__create_rolebinding(
            input=RoleBindingCreateInput(
                ituser=ituser, role=role, validity=SEED_RA_VALIDITY
            )
        )
        return r.uuid

    return inner
