from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from datetime import timezone
from uuid import UUID

import pytest

from mo_smtp.autogenerated_graphql_client import AddressCreateInput
from mo_smtp.autogenerated_graphql_client import ClassCreateInput
from mo_smtp.autogenerated_graphql_client import EmployeeCreateInput
from mo_smtp.autogenerated_graphql_client import EngagementCreateInput
from mo_smtp.autogenerated_graphql_client import FacetCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import ManagerCreateInput
from mo_smtp.autogenerated_graphql_client import OrganisationCreate
from mo_smtp.autogenerated_graphql_client import OrganisationUnitCreateInput
from mo_smtp.autogenerated_graphql_client import RAValidityInput
from mo_smtp.autogenerated_graphql_client import ValidityInput

SEED_FROM = datetime(1930, 1, 1, tzinfo=timezone.utc)
SEED_VALIDITY = ValidityInput(from_=SEED_FROM)
SEED_RA_VALIDITY = RAValidityInput(from_=SEED_FROM)


# --- Root org ---


@pytest.fixture
async def root_org(graphql_client: GraphQLClient) -> UUID:
    """Ensure the root organisation exists."""
    r = await graphql_client._testing__create_org_root(
        input=OrganisationCreate(municipality_code=None)
    )
    return r.uuid


# --- Facet fixtures ---


async def _create_facet(graphql_client: GraphQLClient, user_key: str) -> UUID:
    r = await graphql_client._testing__create_facet(
        input=FacetCreateInput(user_key=user_key, validity=SEED_VALIDITY)
    )
    return r.uuid


@pytest.fixture
async def employee_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "employee_address_type")


@pytest.fixture
async def org_unit_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "org_unit_address_type")


@pytest.fixture
async def org_unit_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_type")


@pytest.fixture
async def engagement_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "engagement_type")


@pytest.fixture
async def engagement_job_function_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "engagement_job_function")


@pytest.fixture
async def role_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "role")


@pytest.fixture
async def manager_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_type")


@pytest.fixture
async def manager_level_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_level")


@pytest.fixture
async def responsibility_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "responsibility")


# --- Class fixtures ---


async def _create_class(
    graphql_client: GraphQLClient,
    facet_uuid: UUID,
    user_key: str,
    name: str,
    scope: str | None = None,
) -> UUID:
    r = await graphql_client._testing__create_class(
        input=ClassCreateInput(
            user_key=user_key,
            name=name,
            facet_uuid=facet_uuid,
            scope=scope,
            validity=SEED_VALIDITY,
        )
    )
    return r.uuid


@pytest.fixture
async def email_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "EmailEmployee", "Email", "EMAIL"
    )


@pytest.fixture
async def phone_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "PhoneEmployee", "Telefon", "PHONE"
    )


@pytest.fixture
async def email_unit(
    graphql_client: GraphQLClient, org_unit_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, org_unit_address_type_facet, "EmailUnit", "Email", "EMAIL"
    )


@pytest.fixture
async def afdeling(graphql_client: GraphQLClient, org_unit_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, org_unit_type_facet, "Afdeling", "Afdeling"
    )


@pytest.fixture
async def ansat(graphql_client: GraphQLClient, engagement_type_facet: UUID) -> UUID:
    return await _create_class(graphql_client, engagement_type_facet, "Ansat", "Ansat")


@pytest.fixture
async def jurist(
    graphql_client: GraphQLClient, engagement_job_function_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, engagement_job_function_facet, "Jurist", "Jurist"
    )


@pytest.fixture
async def niveau1(graphql_client: GraphQLClient, manager_level_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, manager_level_facet, "Niveau1", "Niveau 1"
    )


@pytest.fixture
async def direktoer(graphql_client: GraphQLClient, manager_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, manager_type_facet, "Direktoer", "Direktør"
    )


@pytest.fixture
async def ansvar(graphql_client: GraphQLClient, responsibility_facet: UUID) -> UUID:
    return await _create_class(graphql_client, responsibility_facet, "Ansvar", "Ansvar")


# --- Object factory fixtures ---


@pytest.fixture
def create_employee(
    graphql_client: GraphQLClient,
) -> Callable[[str, str], Awaitable[UUID]]:
    """Return a callable that creates an employee."""

    async def inner(given_name: str, surname: str) -> UUID:
        r = await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name=given_name, surname=surname)
        )
        return r.uuid

    return inner


@pytest.fixture
def create_address(
    graphql_client: GraphQLClient,
) -> Callable[..., Awaitable[UUID]]:
    """Return a callable that creates an address on a person or org unit."""

    async def inner(
        value: str,
        address_type: UUID,
        person: UUID | None = None,
        org_unit: UUID | None = None,
    ) -> UUID:
        r = await graphql_client._testing__create_address(
            input=AddressCreateInput(
                value=value,
                address_type=address_type,
                person=person,
                org_unit=org_unit,
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
async def create_org_unit(
    graphql_client: GraphQLClient, afdeling: UUID
) -> Callable[[str], Awaitable[UUID]]:
    """Return a callable that creates an org unit with the given name."""

    async def inner(name: str) -> UUID:
        r = await graphql_client._testing__create_org_unit(
            input=OrganisationUnitCreateInput(
                name=name,
                org_unit_type=afdeling,
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
async def create_engagement(
    graphql_client: GraphQLClient, ansat: UUID, jurist: UUID
) -> Callable[[UUID, UUID], Awaitable[UUID]]:
    """Return a callable that engages a person in an org unit."""

    async def inner(person: UUID, org_unit: UUID) -> UUID:
        r = await graphql_client._testing__create_engagement(
            input=EngagementCreateInput(
                person=person,
                org_unit=org_unit,
                engagement_type=ansat,
                job_function=jurist,
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
async def create_manager(
    graphql_client: GraphQLClient,
    niveau1: UUID,
    direktoer: UUID,
    ansvar: UUID,
) -> Callable[[UUID, UUID], Awaitable[UUID]]:
    """Return a callable that makes a person manager of an org unit."""

    async def inner(person: UUID, org_unit: UUID) -> UUID:
        r = await graphql_client._testing__create_manager(
            input=ManagerCreateInput(
                person=person,
                org_unit=org_unit,
                manager_level=niveau1,
                manager_type=direktoer,
                responsibility=[ansvar],
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner
