# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from datetime import timezone
from uuid import UUID

import pytest

from mo_smtp.autogenerated_graphql_client import ClassCreateInput
from mo_smtp.autogenerated_graphql_client import FacetCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import OrganisationCreate
from mo_smtp.autogenerated_graphql_client import ValidityInput

SEED_FROM = datetime(1930, 1, 1, tzinfo=timezone.utc)
SEED_VALIDITY = ValidityInput(from_=SEED_FROM)


# --- Root org ---


@pytest.fixture
async def root_org(graphql_client: GraphQLClient) -> UUID:
    """Ensure the root organisation exists."""
    r = await graphql_client._testing__create_org_root(
        input=OrganisationCreate(municipality_code=None)
    )
    return r.uuid


# --- Facet fixtures ---


async def _create_facet(graphql_client: GraphQLClient, user_key: str) -> UUID:
    r = await graphql_client._testing__create_facet(
        input=FacetCreateInput(user_key=user_key, validity=SEED_VALIDITY)
    )
    return r.uuid


@pytest.fixture
async def employee_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "employee_address_type")


@pytest.fixture
async def org_unit_address_type_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "org_unit_address_type")


@pytest.fixture
async def org_unit_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_type")


@pytest.fixture
async def engagement_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "engagement_type")


@pytest.fixture
async def engagement_job_function_facet(
    root_org: UUID, graphql_client: GraphQLClient
) -> UUID:
    return await _create_facet(graphql_client, "engagement_job_function")


@pytest.fixture
async def role_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "role")


@pytest.fixture
async def manager_type_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_type")


@pytest.fixture
async def manager_level_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_level")


@pytest.fixture
async def responsibility_facet(root_org: UUID, graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "responsibility")


# --- Class fixtures ---


async def _create_class(
    graphql_client: GraphQLClient,
    facet_uuid: UUID,
    user_key: str,
    name: str,
    scope: str | None = None,
) -> UUID:
    r = await graphql_client._testing__create_class(
        input=ClassCreateInput(
            user_key=user_key,
            name=name,
            facet_uuid=facet_uuid,
            scope=scope,
            validity=SEED_VALIDITY,
        )
    )
    return r.uuid


@pytest.fixture
async def email_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "EmailEmployee", "Email", "EMAIL"
    )


@pytest.fixture
async def phone_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "PhoneEmployee", "Telefon", "PHONE"
    )


@pytest.fixture
async def email_unit(
    graphql_client: GraphQLClient, org_unit_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, org_unit_address_type_facet, "EmailUnit", "Email", "EMAIL"
    )


@pytest.fixture
async def afdeling(graphql_client: GraphQLClient, org_unit_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, org_unit_type_facet, "Afdeling", "Afdeling"
    )


@pytest.fixture
async def ansat(graphql_client: GraphQLClient, engagement_type_facet: UUID) -> UUID:
    return await _create_class(graphql_client, engagement_type_facet, "Ansat", "Ansat")


@pytest.fixture
async def jurist(
    graphql_client: GraphQLClient, engagement_job_function_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, engagement_job_function_facet, "Jurist", "Jurist"
    )


@pytest.fixture
async def niveau1(graphql_client: GraphQLClient, manager_level_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, manager_level_facet, "Niveau1", "Niveau 1"
    )


@pytest.fixture
async def direktoer(graphql_client: GraphQLClient, manager_type_facet: UUID) -> UUID:
    return await _create_class(
        graphql_client, manager_type_facet, "Direktoer", "Direktør"
    )


@pytest.fixture
async def ansvar(graphql_client: GraphQLClient, responsibility_facet: UUID) -> UUID:
    return await _create_class(graphql_client, responsibility_facet, "Ansvar", "Ansvar")
