# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Integration tests for dataloaders not covered through a handler."""

from datetime import datetime
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest

from mo_smtp.autogenerated_graphql_client import OrganisationUnitTerminateInput
from mo_smtp.dataloaders import get_org_unit_ancestor_uuids

PAST = datetime(2020, 1, 1, tzinfo=ZoneInfo("Europe/Copenhagen"))


@pytest.mark.integration_test
async def test_get_org_unit_ancestor_uuids(graphql_client, create_org_unit) -> None:
    """Returns the org unit's own UUID plus every ancestor's UUID."""
    root = await create_org_unit(name="Root")
    child = await create_org_unit(name="Child", parent=root)
    grandchild = await create_org_unit(name="Grandchild", parent=child)

    # multi-level: self + parent + root
    assert await get_org_unit_ancestor_uuids(graphql_client, grandchild) == {
        grandchild,
        child,
        root,
    }
    # no ancestors: just itself
    assert await get_org_unit_ancestor_uuids(graphql_client, root) == {root}


@pytest.mark.integration_test
async def test_get_org_unit_ancestor_uuids_nonexistent(graphql_client) -> None:
    """A nonexistent org unit yields an empty set (no crash, nothing to match)."""
    assert await get_org_unit_ancestor_uuids(graphql_client, uuid4()) == set()


@pytest.mark.integration_test
async def test_get_org_unit_ancestor_uuids_terminated(
    graphql_client, create_org_unit
) -> None:
    """A terminated org unit yields an empty set: MO's `current`
    field returns no objects for it, so there is nothing to match against.
    The manager handler's own 'org unit terminated' check then short-circuits."""
    root = await create_org_unit(name="Root")
    child = await create_org_unit(name="Child", parent=root)
    await graphql_client._testing__terminate_org_unit(
        input=OrganisationUnitTerminateInput(uuid=child, to=PAST)
    )
    assert await get_org_unit_ancestor_uuids(graphql_client, child) == set()
