# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from uuid import UUID
from zoneinfo import ZoneInfo

import pytest
from httpx import AsyncClient
from more_itertools import one
from structlog.testing import capture_logs

from mo_smtp.autogenerated_graphql_client import EmployeeCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import ITUserTerminateInput
from tests.conftest import Mail

MO_TZ = ZoneInfo("Europe/Copenhagen")
PAST = datetime(2020, 1, 1, tzinfo=MO_TZ)


@pytest.mark.integration_test
@pytest.mark.envvar({"ENABLE_NOTIFICATION_QUEUE": "true"})
async def test_event_queues_and_flush_sends(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
    test_client: AsyncClient,
) -> None:
    """With the queue enabled an event sends nothing; processing the queue
    sends the alert; reprocessing sends nothing further (queue is empty)."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    # The event only queues — no email yet.
    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)
    assert "Notification queued" in str(cap_logs)
    assert await get_sent_mails() == []

    # Processing the queue sends the alert.
    r = await test_client.post("/process_notification_queue")
    assert r.json() == {"processed": 1, "failed": 0}
    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet oprettet i MO"

    # The queue is now empty, so reprocessing sends nothing further.
    r = await test_client.post("/process_notification_queue")
    assert r.json() == {"processed": 0, "failed": 0}
    assert len(await get_sent_mails()) == 1


@pytest.mark.integration_test
@pytest.mark.envvar({"ENABLE_NOTIFICATION_QUEUE": "true"})
async def test_event_burst_coalesces_into_one_email(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
    test_client: AsyncClient,
) -> None:
    """Several events for the same IT-user before the queue is processed result
    in one email, describing the settled state — here the termination."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    # Burst: creation event, then termination event, before any processing.
    await trigger_event("ituser", ituser)
    await graphql_client._testing__terminate_i_t_user(
        input=ITUserTerminateInput(uuid=ituser, to=PAST)
    )
    await trigger_event("ituser", ituser)
    assert await get_sent_mails() == []

    # Both events coalesced into one queued row; processing evaluates the
    # settled (terminated) state once and sends a single email for it.
    r = await test_client.post("/process_notification_queue")
    assert r.json() == {"processed": 1, "failed": 0}
    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet nedlagt i MO"


@pytest.mark.integration_test
async def test_queue_disabled_sends_immediately(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
    test_client: AsyncClient,
) -> None:
    """Without the queue flag (the default) events email immediately, and
    processing the (empty) queue is a no-op."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)
    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet oprettet i MO"

    r = await test_client.post("/process_notification_queue")
    assert r.json() == {"processed": 0, "failed": 0}
    assert len(await get_sent_mails()) == 1
