"""Integration tests for alert_on_ituser and alert_on_rolebinding."""

from datetime import datetime, timedelta
from unittest.mock import MagicMock
from uuid import UUID, uuid4

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from mo_smtp.agents import alert_on_ituser, alert_on_rolebinding
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.models import SentAlert
from sqlalchemy import select


async def _setup_ituser(
    graphql_client: GraphQLClient,
    user_key: str = "ADUSER-123",
) -> tuple[UUID, UUID]:
    """Create employee, IT system, IT user, role, and rolebinding.

    Returns (ituser_uuid, rolebinding_uuid).
    """
    employee = await graphql_client._testing__create_employee(
        first_name="Mick", last_name="Jagger"
    )
    itsystem = await graphql_client._testing__create_it_system(
        name="Active Directory",
        from_=datetime(2010, 1, 1),
    )
    ituser = await graphql_client._testing__create_it_user(
        itsystem=itsystem.uuid,
        person=employee.uuid,
        name=user_key,
        from_=datetime(2010, 1, 1),
        engagements=None,
    )

    role_facet = (await graphql_client._testing__get_role_facet()).objects[0].uuid
    role = await graphql_client._testing__create_class(
        name="admin",
        facet_uuid=role_facet,
        from_=datetime(2010, 1, 1),
    )
    rolebinding = await graphql_client._testing__create_rolebinding(
        ituser=ituser.uuid,
        role=role.uuid,
        from_=datetime(2010, 1, 1),
    )

    return ituser.uuid, rolebinding.uuid


@pytest.mark.integration_test
async def test_ituser_sends_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """An IT user event triggers an alert email."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args
    receiver = call_args.kwargs["receiver"]
    message = call_args.kwargs["body"]
    assert receiver == {"datagruppen@silkeborg.dk"}
    assert "Active Directory" in message
    assert "ADUSER-123" in message
    assert "Mick Jagger" in message


@pytest.mark.integration_test
async def test_rolebinding_sends_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """A rolebinding event resolves to the IT user and sends an alert."""
    _, rolebinding_uuid = await _setup_ituser(graphql_client)

    await alert_on_rolebinding(context, rolebinding_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    message = email_client.send_email.call_args.kwargs["body"]
    assert "Active Directory" in message
    assert "ADUSER-123" in message


@pytest.mark.integration_test
async def test_ituser_dedup_identical_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """Sending the same ituser event twice should only produce one email."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()


@pytest.mark.integration_test
async def test_ituser_content_change_sends_new_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the alert content changes (e.g. a new role is added), the next
    event sends another email and updates the stored content_hash."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    # Add a second role so the rendered template differs from the first run.
    role_facet = (await graphql_client._testing__get_role_facet()).objects[0].uuid
    role2 = await graphql_client._testing__create_class(
        name="reader",
        facet_uuid=role_facet,
        from_=datetime(2010, 1, 1),
    )
    await graphql_client._testing__create_rolebinding(
        ituser=ituser_uuid,
        role=role2.uuid,
        from_=datetime(2010, 1, 1),
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    assert email_client.send_email.call_count == 2


@pytest.mark.integration_test
async def test_ituser_not_found(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the ituser UUID doesn't exist, no email is sent."""
    await alert_on_ituser(context, uuid4(), None, graphql_client, session)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_ituser_default_userkey_is_skipped(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """IT users with the default user_key 'nanoq-brugernavn' are skipped."""
    ituser_uuid, _ = await _setup_ituser(graphql_client, user_key="nanoq-brugernavn")

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_rolebinding_not_found(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When the rolebinding UUID doesn't exist, no email is sent."""
    await alert_on_rolebinding(context, uuid4(), None, graphql_client, session)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_terminated_rolebinding_routes_to_ituser(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """A terminated rolebinding has no current state, but its validities
    still carry the ituser reference. The handler must resolve via
    validities so an event for the deleted rolebinding still produces an
    alert for the (still-alive) ituser."""
    ituser_uuid, rolebinding_uuid = await _setup_ituser(graphql_client)
    await graphql_client._testing__terminate_rolebinding(
        uuid=rolebinding_uuid, to=datetime(2015, 6, 1)
    )

    await alert_on_rolebinding(context, rolebinding_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    body = email_client.send_email.call_args.kwargs["body"]
    assert "ADUSER-123" in body


@pytest.mark.integration_test
async def test_ituser_termination_sends_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """Terminating an IT user produces a termination alert that names the
    person/user_key/itsystem and includes the termination date."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)
    await graphql_client._testing__terminate_it_user(
        uuid=ituser_uuid, to=datetime(2015, 6, 1)
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    call_args = email_client.send_email.call_args
    assert call_args.kwargs["subject"] == "En IT-bruger er blevet termineret i MO"
    body = call_args.kwargs["body"]
    assert "termineret" in body
    assert "Active Directory" in body
    assert "ADUSER-123" in body
    assert "Mick Jagger" in body
    assert "2015-06-01" in body


@pytest.mark.integration_test
async def test_ituser_termination_dedup(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """A repeated event for the same terminated IT user only emails once."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)
    await graphql_client._testing__terminate_it_user(
        uuid=ituser_uuid, to=datetime(2015, 6, 1)
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()


@pytest.mark.integration_test
async def test_ituser_future_termination_sends_termination_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """A termination scheduled for the future should still produce a
    termination alert, not a creation alert. The ituser's `current` state
    is populated (because `to` is in the future), but no validity is
    open-ended, so the handler must treat it as terminated."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)
    midnight = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
    future = midnight + timedelta(days=30)
    await graphql_client._testing__terminate_it_user(uuid=ituser_uuid, to=future)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    assert (
        email_client.send_email.call_args.kwargs["subject"]
        == "En IT-bruger er blevet termineret i MO"
    )


@pytest.mark.integration_test
async def test_ituser_bounded_update_sends_creation_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """A bounded update (user_key changed for a fixed period) leaves a
    trailing open-ended validity for the resumed state, so the handler must
    not flag the ituser as terminated."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)
    midnight = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
    yesterday = midnight - timedelta(days=1)
    tomorrow = midnight + timedelta(days=1)
    await graphql_client._testing__update_it_user(
        uuid=ituser_uuid,
        user_key="TEMPORARY",
        from_=yesterday,
        to=tomorrow,
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    assert (
        email_client.send_email.call_args.kwargs["subject"]
        == "En IT-bruger er blevet oprettet i MO"
    )


@pytest.mark.integration_test
async def test_ituser_open_ended_update_sends_new_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """A permanent (open-ended) user_key change produces a new alert: the
    timeline grows from one validity to two, but the latest still has
    to=None, so the ituser is not terminated and the rendered body changes."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)
    midnight = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    await graphql_client._testing__update_it_user(
        uuid=ituser_uuid, user_key="ADUSER-456", from_=midnight
    )
    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    assert email_client.send_email.call_count == 2
    second_body = email_client.send_email.call_args_list[1].kwargs["body"]
    assert "ADUSER-456" in second_body


@pytest.mark.integration_test
async def test_ituser_create_then_terminate(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """The full lifecycle: a creation event sends a creation alert, then a
    termination event sends a separate termination alert. Both dedup rows
    coexist (different alert_type)."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    await graphql_client._testing__terminate_it_user(
        uuid=ituser_uuid, to=datetime(2015, 6, 1)
    )
    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    assert email_client.send_email.call_count == 2
    subjects = [c.kwargs["subject"] for c in email_client.send_email.call_args_list]
    assert subjects == [
        "En IT-bruger er blevet oprettet i MO",
        "En IT-bruger er blevet termineret i MO",
    ]


@pytest.mark.integration_test
async def test_ituser_terminate_after_update_uses_latest_validity(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When an ituser has been updated and then terminated, the termination
    email reports the most recent state (post-update user_key)."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)
    await graphql_client._testing__update_it_user(
        uuid=ituser_uuid, user_key="ADUSER-RENAMED", from_=datetime(2012, 1, 1)
    )
    await graphql_client._testing__terminate_it_user(
        uuid=ituser_uuid, to=datetime(2015, 6, 1)
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    email_client.send_email.assert_called_once()
    body = email_client.send_email.call_args.kwargs["body"]
    assert "ADUSER-RENAMED" in body
    assert "ADUSER-123" not in body
    assert "2015-06-01" in body


@pytest.mark.integration_test
async def test_ituser_without_person_skipped(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """An org_unit-scoped IT user (no person attached) is silently skipped:
    there's no individual to notify anyone about."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    root = await graphql_client._testing__create_org_unit_root(
        name="Root",
        root_uuid=uuid4(),
        org_unit_type=org_unit_type,
        from_=datetime(2010, 1, 1),
    )
    itsystem = await graphql_client._testing__create_it_system(
        name="AD", from_=datetime(2010, 1, 1)
    )
    ituser = await graphql_client._testing__create_org_unit_it_user(
        itsystem=itsystem.uuid,
        org_unit=root.uuid,
        name="SVC-ACCT",
        from_=datetime(2010, 1, 1),
    )

    await alert_on_ituser(context, ituser.uuid, None, graphql_client, session)
    email_client.send_email.assert_not_called()


@pytest.mark.integration_test
async def test_ituser_termination_content_change_sends_new_email(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """When a termination row exists with a stale content_hash, the next
    event re-sends the alert and updates the row. Exercises the
    'existing.content_hash = content_hash' branch on the termination path."""
    ituser_uuid, _ = await _setup_ituser(graphql_client)
    await graphql_client._testing__terminate_it_user(
        uuid=ituser_uuid, to=datetime(2015, 6, 1)
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    email_client.send_email.assert_called_once()

    row = await session.scalar(
        select(SentAlert).where(
            SentAlert.alert_type == "ituser_termination",
            SentAlert.object_uuid == ituser_uuid,
        )
    )
    assert row is not None
    original_hash = row.content_hash
    row.content_hash = "stale-hash-from-an-earlier-deploy"
    await session.flush()

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)

    assert email_client.send_email.call_count == 2
    refreshed = await session.scalar(
        select(SentAlert).where(
            SentAlert.alert_type == "ituser_termination",
            SentAlert.object_uuid == ituser_uuid,
        )
    )
    assert refreshed is not None
    assert refreshed.content_hash == original_hash


@pytest.mark.integration_test
async def test_ituser_termination_default_userkey_skipped(
    context,
    session: AsyncSession,
    graphql_client: GraphQLClient,
    email_client: MagicMock,
):
    """nanoq-brugernavn itusers are skipped on termination too."""
    ituser_uuid, _ = await _setup_ituser(graphql_client, user_key="nanoq-brugernavn")
    await graphql_client._testing__terminate_it_user(
        uuid=ituser_uuid, to=datetime(2015, 6, 1)
    )

    await alert_on_ituser(context, ituser_uuid, None, graphql_client, session)
    email_client.send_email.assert_not_called()
