# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from collections.abc import Awaitable
from collections.abc import Callable
from datetime import date
from datetime import datetime
from uuid import UUID
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
from more_itertools import one
from structlog.testing import capture_logs

from mo_smtp.agents import load_template
from mo_smtp.autogenerated_graphql_client import EmployeeCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import ITUserTerminateInput
from tests.conftest import Mail

MO_TZ = ZoneInfo("Europe/Copenhagen")
PAST = datetime(2020, 1, 1, tzinfo=MO_TZ)


@pytest.mark.integration_test
async def test_ituser_not_found(
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """A non-existent IT-user UUID sends no email."""
    with capture_logs() as cap_logs:
        await trigger_event("ituser", uuid4())

    assert "IT-user doesn't exist" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_ituser_without_person_is_ignored(
    active_directory: UUID,
    create_org_unit: Callable[..., Awaitable[UUID]],
    create_ituser: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """An org_unit-scoped IT-user has no person to notify about, so no email is sent."""
    org_unit = await create_org_unit(name="Some Unit")
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, org_unit=org_unit
    )

    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)

    assert "IT-user has no person. An email will not be sent" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_ituser_default_userkey_is_ignored(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """An IT-user with the default user_key 'nanoq-brugernavn' sends no email."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="nanoq-brugernavn", itsystem=active_directory, person=person
    )

    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)

    assert "default user_key 'nanoq-brugernavn'" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_ituser_sends_email(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """A new IT-user triggers a notice to datagruppen describing the IT-user."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)

    # All inputs are fixed, so the whole email is deterministic: assert it equals
    # the template rendered with the expected context.
    expected_body = load_template("alert_on_rolebinding.html").render(
        context={
            "person": "Mick Jagger",
            "ituser": "ADUSER-123",
            "itsystem": "Active Directory",
            "roles": [{"name": "Rolle"}],
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet oprettet i MO"
    assert mail.recipients == ["<datagruppen@silkeborg.dk>"]
    assert mail.html is not None
    assert mail.html.strip() == expected_body.strip()


@pytest.mark.integration_test
async def test_ituser_identical_email_is_deduplicated(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """Re-triggering the same IT-user does not send a second email."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)
    assert len(await get_sent_mails()) == 1

    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)

    assert "An identical alert has already been sent. An email will not be sent" in str(
        cap_logs
    )
    assert len(await get_sent_mails()) == 1


@pytest.mark.integration_test
async def test_ituser_re_alerts_and_updates_hash_when_content_changes(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    rolle2: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """Changed IT-user content re-alerts and records the new hash, so the changed
    state then deduplicates against itself rather than the original content."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)
    assert len(await get_sent_mails()) == 1

    # Content changes (a second role), so a fresh alert is sent and its hash stored.
    await create_rolebinding(ituser=ituser, role=rolle2)
    await trigger_event("ituser", ituser)
    assert len(await get_sent_mails()) == 2

    # The stored hash now matches the changed content, so a repeat is deduplicated.
    # If the hash had not been updated, this would send a third email.
    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)

    assert "An identical alert has already been sent. An email will not be sent" in str(
        cap_logs
    )
    assert len(await get_sent_mails()) == 2


@pytest.mark.integration_test
async def test_ituser_termination_sends_email(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """Terminating an IT-user sends a 'nedlagt' notice — and because the
    termination date is part of the dedup content, it re-alerts past the
    earlier creation rather than being deduplicated against it."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    # Created → first alert.
    await trigger_event("ituser", ituser)
    assert len(await get_sent_mails()) == 1

    # Terminated → the content now carries a to_date, so it re-alerts.
    await graphql_client._testing__terminate_i_t_user(
        input=ITUserTerminateInput(uuid=ituser, to=PAST)
    )
    await trigger_event("ituser", ituser)

    # All inputs are fixed, so the whole email is deterministic: assert it equals
    # the template rendered with the expected context. The roles also prove that
    # MO resolves rolebindings within the terminated validity.
    expected_body = load_template("alert_on_rolebinding.html").render(
        context={
            "person": "Mick Jagger",
            "ituser": "ADUSER-123",
            "itsystem": "Active Directory",
            "roles": [{"name": "Rolle"}],
            "terminated": True,
            "to_date": date(2020, 1, 1),
        }
    )
    mails = await get_sent_mails()
    assert len(mails) == 2
    termination = one(
        m for m in mails if m.subject == "En IT-bruger er blevet nedlagt i MO"
    )
    assert termination.recipients == ["<datagruppen@silkeborg.dk>"]
    assert termination.html is not None
    assert termination.html.strip() == expected_body.strip()
