# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import date
from datetime import datetime
from datetime import timezone
from uuid import UUID
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
from more_itertools import one
from structlog.testing import capture_logs

from mo_smtp.agents import load_template
from mo_smtp.autogenerated_graphql_client import AddressCreateInput
from mo_smtp.autogenerated_graphql_client import EmployeeCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import ManagerTerminateInput
from mo_smtp.autogenerated_graphql_client import OrganisationUnitTerminateInput
from mo_smtp.autogenerated_graphql_client import RAValidityInput

# MO normalizes termination dates to Europe/Copenhagen and requires them to fall
# at midnight there; a UTC midnight becomes 01:00 CET and is rejected.
MO_TZ = ZoneInfo("Europe/Copenhagen")
PAST = datetime(2020, 1, 1, tzinfo=MO_TZ)
FUTURE = datetime(2099, 1, 1, tzinfo=MO_TZ)
# Validity for created objects — far enough in the past that they're current.
SEED = RAValidityInput(from_=datetime(1930, 1, 1, tzinfo=timezone.utc))


@pytest.mark.integration_test
async def test_manager_not_found(trigger_event, get_sent_mails) -> None:
    """A non-existent manager UUID sends no email."""
    with capture_logs() as cap_logs:
        await trigger_event("manager", uuid4())

    assert "Manager not found" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_currently_employed_manager_is_ignored(
    graphql_client: GraphQLClient,
    create_org_unit,
    create_manager,
    trigger_event,
    get_sent_mails,
) -> None:
    """A manager who is still employed (open validity) sends no email."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Keith", surname="Richards")
        )
    ).uuid
    org_unit = await create_org_unit(name="Stones")
    manager = await create_manager(person=person, org_unit=org_unit)

    with capture_logs() as cap_logs:
        await trigger_event("manager", manager)

    assert "Manager is currently employed" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_terminated_manager_sends_email(
    graphql_client: GraphQLClient,
    create_org_unit,
    create_manager,
    trigger_event,
    get_sent_mails,
) -> None:
    """A manager terminated in the past triggers a removal notice to datagruppen."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Keith", surname="Richards")
        )
    ).uuid
    org_unit = await create_org_unit(name="Stones", user_key="stones")
    manager = await create_manager(person=person, org_unit=org_unit)
    await graphql_client._testing__terminate_manager(
        input=ManagerTerminateInput(uuid=manager, to=PAST)
    )

    await trigger_event("manager", manager)

    # All inputs are fixed, so the whole email is deterministic: assert it equals
    # the termination template rendered with the expected context (which also
    # proves the terminated branch — not the vacant one — was taken).
    expected_body = load_template("alert_on_manager_termination.html").render(
        context={
            "name": "Keith Richards",
            "to_date": date(2020, 1, 1),
            "location": "Stones",
            "user_key": "stones",
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En medarbejder er blevet fjernet fra lederfanen"
    assert mail.recipients == ["<datagruppen@silkeborg.dk>"]
    assert mail.html.strip() == expected_body.strip()


@pytest.mark.integration_test
async def test_vacant_manager_sends_email(
    create_org_unit,
    create_manager,
    trigger_event,
    get_sent_mails,
) -> None:
    """A vacant manager role (no person) triggers a vacancy notice."""
    org_unit = await create_org_unit(name="Stones", user_key="stones")
    manager = await create_manager(person=None, org_unit=org_unit)

    await trigger_event("manager", manager)

    # A vacant manager has no person, so the agent uses the name "Vacant manager"
    # and the vacancy date is the role's start date (the SEED validity, 1930).
    expected_body = load_template("alert_on_vacant_manager.html").render(
        context={
            "name": "Vacant manager",
            "to_date": date(1930, 1, 1),
            "location": "Stones",
            "user_key": "stones",
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En medarbejder er blevet fjernet fra lederfanen"
    assert mail.recipients == ["<datagruppen@silkeborg.dk>"]
    assert mail.html.strip() == expected_body.strip()


@pytest.mark.integration_test
async def test_future_terminated_manager_is_ignored(
    graphql_client: GraphQLClient,
    create_org_unit,
    create_manager,
    trigger_event,
    get_sent_mails,
) -> None:
    """A manager terminated in the future sends no email (yet)."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Keith", surname="Richards")
        )
    ).uuid
    org_unit = await create_org_unit(name="Stones")
    manager = await create_manager(person=person, org_unit=org_unit)
    await graphql_client._testing__terminate_manager(
        input=ManagerTerminateInput(uuid=manager, to=FUTURE)
    )

    with capture_logs() as cap_logs:
        await trigger_event("manager", manager)

    assert "to_date is in the future" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "True"})
async def test_terminated_manager_emails_org_unit(
    graphql_client: GraphQLClient,
    create_org_unit,
    create_manager,
    email_unit: UUID,
    trigger_event,
    get_sent_mails,
) -> None:
    """With org-unit emails enabled, the notice goes to the unit's email, not datagruppen."""
    root = await create_org_unit(name="Root")
    institution = await create_org_unit(
        name="Institution", user_key="inst", parent=root
    )
    await graphql_client._testing__create_address(
        input=AddressCreateInput(
            value="institution@example.com",
            address_type=email_unit,
            org_unit=institution,
            validity=SEED,
        )
    )

    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Keith", surname="Richards")
        )
    ).uuid
    manager = await create_manager(person=person, org_unit=institution)
    await graphql_client._testing__terminate_manager(
        input=ManagerTerminateInput(uuid=manager, to=PAST)
    )

    await trigger_event("manager", manager)

    expected_body = load_template("alert_on_manager_termination.html").render(
        context={
            "name": "Keith Richards",
            "to_date": date(2020, 1, 1),
            "location": "Root / Institution",
            "user_key": "inst",
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En medarbejder er blevet fjernet fra lederfanen"
    assert mail.recipients == ["<institution@example.com>"]
    assert mail.html.strip() == expected_body.strip()


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "True"})
async def test_terminated_manager_deep_in_tree_emails_institution(
    graphql_client: GraphQLClient,
    create_org_unit,
    create_manager,
    email_unit: UUID,
    trigger_event,
    get_sent_mails,
) -> None:
    """For a manager deep in the tree, the mail goes to the institution (child of root).

    Root > Institution > Dept > Team: the recipient is resolved by walking down
    from the root to the top-level unit on the path (Institution), not the root
    itself nor the manager's own deep unit.
    """
    root = await create_org_unit(name="Root")
    institution = await create_org_unit(
        name="Institution", user_key="inst", parent=root
    )
    dept = await create_org_unit(name="Dept", parent=institution)
    team = await create_org_unit(name="Team", user_key="team", parent=dept)
    # Email lives on the institution; the manager is three levels below the root.
    await graphql_client._testing__create_address(
        input=AddressCreateInput(
            value="institution@example.com",
            address_type=email_unit,
            org_unit=institution,
            validity=SEED,
        )
    )

    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Keith", surname="Richards")
        )
    ).uuid
    manager = await create_manager(person=person, org_unit=team)
    await graphql_client._testing__terminate_manager(
        input=ManagerTerminateInput(uuid=manager, to=PAST)
    )

    await trigger_event("manager", manager)

    expected_body = load_template("alert_on_manager_termination.html").render(
        context={
            "name": "Keith Richards",
            "to_date": date(2020, 1, 1),
            "location": "Root / Institution / Dept / Team",
            "user_key": "team",
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En medarbejder er blevet fjernet fra lederfanen"
    assert mail.recipients == ["<institution@example.com>"]
    assert mail.html.strip() == expected_body.strip()


@pytest.mark.integration_test
async def test_terminated_manager_with_terminated_org_unit_is_ignored(
    graphql_client: GraphQLClient,
    create_org_unit,
    create_manager,
    trigger_event,
    get_sent_mails,
) -> None:
    """If the manager's org unit is itself terminated, no email is sent."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Keith", surname="Richards")
        )
    ).uuid
    org_unit = await create_org_unit(name="Stones")
    manager = await create_manager(person=person, org_unit=org_unit)
    await graphql_client._testing__terminate_manager(
        input=ManagerTerminateInput(uuid=manager, to=PAST)
    )
    await graphql_client._testing__terminate_org_unit(
        input=OrganisationUnitTerminateInput(uuid=org_unit, to=PAST)
    )

    with capture_logs() as cap_logs:
        await trigger_event("manager", manager)

    assert "Org unit is possibly terminated or doesn't exist" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "True"})
async def test_terminated_manager_on_root_emails_root_unit(
    graphql_client: GraphQLClient,
    create_org_unit,
    create_manager,
    email_unit: UUID,
    trigger_event,
    get_sent_mails,
) -> None:
    """A manager on the root unit (org_unit == root) emails that unit directly."""
    root = await create_org_unit(name="Root", user_key="root")
    # Give Root a multi-level subtree; the manager still sits on Root itself,
    # so org_unit == root and the mail goes to Root's own address.
    institution = await create_org_unit(name="Institution", parent=root)
    await create_org_unit(name="Dept", parent=institution)
    await graphql_client._testing__create_address(
        input=AddressCreateInput(
            value="root@example.com",
            address_type=email_unit,
            org_unit=root,
            validity=SEED,
        )
    )

    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Keith", surname="Richards")
        )
    ).uuid
    manager = await create_manager(person=person, org_unit=root)
    await graphql_client._testing__terminate_manager(
        input=ManagerTerminateInput(uuid=manager, to=PAST)
    )

    await trigger_event("manager", manager)

    expected_body = load_template("alert_on_manager_termination.html").render(
        context={
            "name": "Keith Richards",
            "to_date": date(2020, 1, 1),
            "location": "Root",
            "user_key": "root",
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En medarbejder er blevet fjernet fra lederfanen"
    assert mail.recipients == ["<root@example.com>"]
    assert mail.html.strip() == expected_body.strip()
