# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from uuid import UUID
from uuid import uuid4

import pytest
from more_itertools import one
from structlog.testing import capture_logs

from mo_smtp.agents import load_template
from mo_smtp.autogenerated_graphql_client import EmployeeCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_ituser_not_found(trigger_event, get_sent_mails) -> None:
    """A non-existent IT-user UUID sends no email."""
    with capture_logs() as cap_logs:
        await trigger_event("ituser", uuid4())

    assert "IT-user is possibly terminated or doesn't exist" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_ituser_default_userkey_is_ignored(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    create_ituser,
    trigger_event,
    get_sent_mails,
) -> None:
    """An IT-user with the default user_key 'nanoq-brugernavn' sends no email."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="nanoq-brugernavn", itsystem=active_directory, person=person
    )

    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)

    assert "default user_key 'nanoq-brugernavn'" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_ituser_sends_email(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser,
    create_rolebinding,
    trigger_event,
    get_sent_mails,
) -> None:
    """A new IT-user triggers a notice to datagruppen describing the IT-user."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)

    # All inputs are fixed, so the whole email is deterministic: assert it equals
    # the template rendered with the expected context.
    expected_body = load_template("alert_on_rolebinding.html").render(
        context={
            "person": "Mick Jagger",
            "ituser": "ADUSER-123",
            "itsystem": "Active Directory",
            "roles": [{"name": "Rolle"}],
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet oprettet i MO"
    assert mail.recipients == ["<datagruppen@silkeborg.dk>"]
    assert mail.html.strip() == expected_body.strip()


@pytest.mark.integration_test
async def test_ituser_identical_email_is_deduplicated(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser,
    create_rolebinding,
    trigger_event,
    get_sent_mails,
) -> None:
    """Re-triggering the same IT-user does not send a second email."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)
    assert len(await get_sent_mails()) == 1

    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)

    assert "An identical alert has already been sent. An email will not be sent" in str(
        cap_logs
    )
    assert len(await get_sent_mails()) == 1


@pytest.mark.integration_test
async def test_ituser_re_alerts_and_updates_hash_when_content_changes(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    rolle2: UUID,
    create_ituser,
    create_rolebinding,
    trigger_event,
    get_sent_mails,
) -> None:
    """Changed IT-user content re-alerts and records the new hash, so the changed
    state then deduplicates against itself rather than the original content."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)
    assert len(await get_sent_mails()) == 1

    # Content changes (a second role), so a fresh alert is sent and its hash stored.
    await create_rolebinding(ituser=ituser, role=rolle2)
    await trigger_event("ituser", ituser)
    assert len(await get_sent_mails()) == 2

    # The stored hash now matches the changed content, so a repeat is deduplicated.
    # If the hash had not been updated, this would send a third email.
    with capture_logs() as cap_logs:
        await trigger_event("ituser", ituser)

    assert "An identical alert has already been sent. An email will not be sent" in str(
        cap_logs
    )
    assert len(await get_sent_mails()) == 2
