# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from uuid import UUID
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
from more_itertools import one
from structlog.testing import capture_logs

from mo_smtp.agents import load_template
from mo_smtp.autogenerated_graphql_client import EmployeeCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import RoleBindingTerminateInput

# MO normalizes termination dates to Europe/Copenhagen and requires them to fall
# at midnight there; a UTC midnight becomes 01:00 CET and is rejected.
MO_TZ = ZoneInfo("Europe/Copenhagen")
PAST = datetime(2020, 1, 1, tzinfo=MO_TZ)


@pytest.mark.integration_test
async def test_rolebinding_not_found(trigger_event, get_sent_mails) -> None:
    """A rolebinding UUID that resolves to no IT-user sends no email."""
    with capture_logs() as cap_logs:
        await trigger_event("rolebinding", uuid4())

    assert "IT-user is possibly terminated or doesn't exist" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_rolebinding_terminated_is_ignored(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser,
    create_rolebinding,
    trigger_event,
    get_sent_mails,
) -> None:
    """A terminated rolebinding has no current validity, so no email is sent."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    rolebinding = await create_rolebinding(ituser=ituser, role=rolle)
    await graphql_client._testing__terminate_rolebinding(
        input=RoleBindingTerminateInput(uuid=rolebinding, to=PAST)
    )

    with capture_logs() as cap_logs:
        await trigger_event("rolebinding", rolebinding)

    assert "IT-user is possibly terminated or doesn't exist" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_rolebinding_default_userkey_is_ignored(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser,
    create_rolebinding,
    trigger_event,
    get_sent_mails,
) -> None:
    """An IT-user with the default user_key 'nanoq-brugernavn' sends no email."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="nanoq-brugernavn", itsystem=active_directory, person=person
    )
    rolebinding = await create_rolebinding(ituser=ituser, role=rolle)

    with capture_logs() as cap_logs:
        await trigger_event("rolebinding", rolebinding)

    assert "default user_key 'nanoq-brugernavn'" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_rolebinding_sends_email(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser,
    create_rolebinding,
    trigger_event,
    get_sent_mails,
) -> None:
    """A new rolebinding triggers a notice to datagruppen describing the IT-user."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    rolebinding = await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("rolebinding", rolebinding)

    # All inputs are fixed, so the whole email is deterministic: assert it equals
    # the template rendered with the expected context.
    expected_body = load_template("alert_on_rolebinding.html").render(
        context={
            "person": "Mick Jagger",
            "ituser": "ADUSER-123",
            "itsystem": "Active Directory",
            "roles": [{"name": "Rolle"}],
        }
    )
    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet oprettet i MO"
    assert mail.recipients == ["<datagruppen@silkeborg.dk>"]
    assert mail.html.strip() == expected_body.strip()


@pytest.mark.integration_test
async def test_rolebinding_identical_email_is_deduplicated(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser,
    create_rolebinding,
    trigger_event,
    get_sent_mails,
) -> None:
    """Re-triggering an identical rolebinding does not send a second email."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    rolebinding = await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("rolebinding", rolebinding)
    assert len(await get_sent_mails()) == 1

    with capture_logs() as cap_logs:
        await trigger_event("rolebinding", rolebinding)

    assert "Email is identical to the previous" in str(cap_logs)
    assert len(await get_sent_mails()) == 1
