# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""The notification send schedule batches alerts of every type: off-schedule
events are deferred with X-Not-Before and wait in the event system."""

from collections.abc import Awaitable
from collections.abc import Callable
from datetime import date
from datetime import datetime
from datetime import time
from uuid import UUID
from uuid import uuid4

import pytest
from httpx import AsyncClient
from more_itertools import one

from mo_smtp.autogenerated_graphql_client import EmployeeCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from tests.conftest import Mail


@pytest.mark.integration_test
@pytest.mark.envvar({"NOTIFICATION_SEND_SCHEDULE": "0 0 1 1 *"})
async def test_off_schedule_event_is_deferred(
    test_client: AsyncClient,
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """With a send schedule of midnight January 1st, an event at any other time
    responds 425 with X-Not-Before = the next tick, so it waits in the event
    system instead of mailing during the day."""
    r = await test_client.post("/ituser", json={"subject": str(uuid4()), "priority": 1})

    assert r.status_code == 425
    not_before = datetime.fromisoformat(r.headers["X-Not-Before"])
    assert not_before > datetime.now().astimezone()
    assert (not_before.month, not_before.day, not_before.hour) == (1, 1, 0)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
@pytest.mark.envvar({"NOTIFICATION_SEND_SCHEDULE": "0 0 1 1 *"})
async def test_schedule_applies_to_every_alert_type(
    test_client: AsyncClient,
) -> None:
    """The schedule is not IT-user specific: every event endpoint defers."""
    for path in ("/manager", "/rolebinding", "/org_unit", "/related_unit"):
        r = await test_client.post(path, json={"subject": str(uuid4()), "priority": 1})
        assert r.status_code == 425, path
        assert "X-Not-Before" in r.headers, path


@pytest.mark.integration_test
@pytest.mark.envvar({"NOTIFICATION_SEND_SCHEDULE": "0 0 * * *"})
async def test_redelivered_batch_event_stays_due_while_draining(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    test_client: AsyncClient,
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """An event redelivered with the X-Not-Before it was deferred to (here:
    last midnight's tick) is sent even though the tick's minute has passed —
    a large batch keeps draining until the next tick."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    last_midnight = datetime.combine(date.today(), time()).astimezone()
    r = await test_client.post(
        "/ituser",
        json={"subject": str(ituser), "priority": 1},
        headers={"X-Not-Before": last_midnight.isoformat()},
    )

    assert r.status_code == 200
    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet oprettet i MO"


@pytest.mark.integration_test
@pytest.mark.envvar({"NOTIFICATION_SEND_SCHEDULE": "* * * * *"})
async def test_at_send_time_the_alert_is_sent(
    graphql_client: GraphQLClient,
    active_directory: UUID,
    rolle: UUID,
    create_ituser: Callable[..., Awaitable[UUID]],
    create_rolebinding: Callable[..., Awaitable[UUID]],
    trigger_event: Callable[[str, UUID], Awaitable[None]],
    get_sent_mails: Callable[[], Awaitable[list[Mail]]],
) -> None:
    """An every-minute schedule means it is always send time, so the alert goes
    out right away."""
    person = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Mick", surname="Jagger")
        )
    ).uuid
    ituser = await create_ituser(
        user_key="ADUSER-123", itsystem=active_directory, person=person
    )
    await create_rolebinding(ituser=ituser, role=rolle)

    await trigger_event("ituser", ituser)

    mail = one(await get_sent_mails())
    assert mail.subject == "En IT-bruger er blevet oprettet i MO"
