# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from datetime import datetime
from datetime import timezone
from uuid import UUID
from uuid import uuid4

import pytest
from more_itertools import one
from structlog.testing import capture_logs

from mo_smtp.autogenerated_graphql_client import AddressCreateInput
from mo_smtp.autogenerated_graphql_client import GraphQLClient
from mo_smtp.autogenerated_graphql_client import RAValidityInput

SEED = RAValidityInput(from_=datetime(1930, 1, 1, tzinfo=timezone.utc))


@pytest.mark.integration_test
async def test_org_unit_not_found(trigger_event, get_sent_mails) -> None:
    """A non-existent org unit UUID sends no email."""
    with capture_logs() as cap_logs:
        await trigger_event("org_unit", uuid4())

    assert "Org unit not found" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_org_unit_outside_loenorg_is_ignored(
    create_org_unit,
    trigger_event,
    get_sent_mails,
) -> None:
    """An org unit whose root is not the Lønorganisation sends no email."""
    adm_org = await create_org_unit(name="Administration")
    adm_unit = await create_org_unit(name="Adm-enhed", parent=adm_org)

    with capture_logs() as cap_logs:
        await trigger_event("org_unit", adm_unit)

    assert "Org unit is not in the Lønorganisation" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_org_unit_with_relation_sends_no_email(
    root_loen_org: UUID,
    create_org_unit,
    create_related_units,
    trigger_event,
    get_sent_mails,
) -> None:
    """A lønorg unit that still relates to an administration unit sends no email."""
    loen_root = await create_org_unit(name="Lønorganisation", uuid=root_loen_org)
    loen_unit = await create_org_unit(name="Løn-enhed", parent=loen_root)
    adm_org = await create_org_unit(name="Administration")
    adm_unit = await create_org_unit(name="Adm-enhed", parent=adm_org)
    await create_related_units(origin=loen_unit, destination=[adm_unit])

    with capture_logs() as cap_logs:
        await trigger_event("org_unit", loen_unit)

    assert "Org unit has a relation outside of the Lønorganisation" in str(cap_logs)
    assert await get_sent_mails() == []


@pytest.mark.integration_test
async def test_org_unit_without_relation_sends_email(
    root_loen_org: UUID,
    create_org_unit,
    trigger_event,
    get_sent_mails,
    missing_relation_body,
) -> None:
    """A lønorg unit with no administration relation sends email."""
    loen_root = await create_org_unit(name="Lønorganisation", uuid=root_loen_org)
    loen_unit = await create_org_unit(name="Løn-enhed", parent=loen_root)

    await trigger_event("org_unit", loen_unit)

    mail = one(await get_sent_mails())
    assert mail.subject == "Manglende relation i Lønorganisation"
    assert mail.recipients == ["<datagruppen@silkeborg.dk>"]
    assert mail.plain.strip() == missing_relation_body("Løn-enhed")


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "True"})
async def test_org_unit_without_relation_emails_institution(
    graphql_client: GraphQLClient,
    root_loen_org: UUID,
    create_org_unit,
    email_unit: UUID,
    trigger_event,
    get_sent_mails,
    missing_relation_body,
) -> None:
    """With USE_ORG_UNIT_EMAILS=True, the alert goes to the unit's institution email."""
    loen_root = await create_org_unit(name="Lønorganisation", uuid=root_loen_org)
    institution = await create_org_unit(name="Institution", parent=loen_root)
    await graphql_client._testing__create_address(
        input=AddressCreateInput(
            value="institution@example.com",
            address_type=email_unit,
            org_unit=institution,
            validity=SEED,
        )
    )
    loen_unit = await create_org_unit(name="Løn-enhed", parent=institution)

    await trigger_event("org_unit", loen_unit)

    mail = one(await get_sent_mails())
    assert mail.subject == "Manglende relation i Lønorganisation"
    assert mail.recipients == ["<institution@example.com>"]
    assert mail.plain.strip() == missing_relation_body("Løn-enhed")


@pytest.mark.integration_test
@pytest.mark.envvar({"ALERT_MANAGER_REMOVAL_USE_ORG_UNIT_EMAILS": "True"})
async def test_loen_root_without_relation_uses_own_email(
    graphql_client: GraphQLClient,
    root_loen_org: UUID,
    create_org_unit,
    email_unit: UUID,
    trigger_event,
    get_sent_mails,
    missing_relation_body,
) -> None:
    """When USE_ORG_UNIT_EMAILS=True and the lønorg root itself lacks a relation, it emails its own address."""
    loen_root = await create_org_unit(name="Lønorganisation", uuid=root_loen_org)
    await graphql_client._testing__create_address(
        input=AddressCreateInput(
            value="loenorg@example.com",
            address_type=email_unit,
            org_unit=loen_root,
            validity=SEED,
        )
    )

    await trigger_event("org_unit", loen_root)

    mail = one(await get_sent_mails())
    assert mail.subject == "Manglende relation i Lønorganisation"
    assert mail.recipients == ["<loenorg@example.com>"]
    assert mail.plain.strip() == missing_relation_body("Lønorganisation")
