# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""HTTP endpoints that handle GraphQL events from MO."""

import datetime
import hashlib
import json
import os
from uuid import UUID

import structlog
from fastapi import APIRouter
from fastramqpi.events import Event
from jinja2 import Environment
from jinja2 import FileSystemLoader
from more_itertools import one
from sqlalchemy import delete
from sqlalchemy import exists
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from . import depends
from .autogenerated_graphql_client.employee_name import (
    EmployeeNameEmployeesObjectsCurrent,
)
from .autogenerated_graphql_client.ituser_validities import (
    ItuserValiditiesItusersObjectsValidities,
)
from .dataloaders import get_employee_name
from .dataloaders import get_institution_address
from .dataloaders import get_ituser_uuid_by_rolebinding
from .dataloaders import get_ituser_validities
from .dataloaders import get_manager_data
from .dataloaders import get_org_unit_address
from .dataloaders import get_org_unit_ancestor_uuids
from .dataloaders import get_org_unit_data
from .dataloaders import get_org_unit_location
from .dataloaders import get_org_unit_relations
from .dataloaders import get_org_unit_root
from .dataloaders import get_related_units_data
from .dataloaders import root_uuid
from .helpers import defer_until_advance_notice
from .helpers import extract_current_or_latest_validity
from .mail import EmailClient
from .models import SentAlert

logger = structlog.get_logger()


router = APIRouter()


def load_template(filename):
    templates_folder = os.path.join(os.path.dirname(__file__), "email_templates")
    file_loader = FileSystemLoader(templates_folder)
    env = Environment(loader=file_loader)
    template = env.get_template(filename)

    return template


def _content_hash(content: dict) -> str:
    return hashlib.sha256(
        json.dumps(content, sort_keys=True, default=str).encode()
    ).hexdigest()


async def _content_alert_already_sent(
    session: AsyncSession,
    alert_type: str,
    object_uuid: UUID,
    content: dict,
) -> bool:
    """Whether an alert with identical content was already sent for this object.

    Used for the per-object notification alerts (ituser, manager); relation
    alerts dedup on row presence instead (see
    _check_and_alert_org_unit_without_relation). Pair with _record_content_alert,
    called only after the email is actually sent.
    """
    return bool(
        await session.scalar(
            select(
                exists().where(
                    SentAlert.alert_type == alert_type,
                    SentAlert.object_uuid == object_uuid,
                    SentAlert.content_hash == _content_hash(content),
                )
            )
        )
    )


async def _record_content_alert(
    session: AsyncSession,
    alert_type: str,
    object_uuid: UUID,
    content: dict,
) -> None:
    """Record the alert just sent for this object (one row per object per type).

    Upserts on the (alert_type, object_uuid) unique constraint, so a concurrent
    insert for the same object becomes an update rather than a constraint error.
    """
    content_hash = _content_hash(content)
    stmt = (
        pg_insert(SentAlert)
        .values(
            alert_type=alert_type,
            object_uuid=object_uuid,
            content_hash=content_hash,
        )
        .on_conflict_do_update(
            index_elements=["alert_type", "object_uuid"],
            set_={"content_hash": content_hash},
        )
    )
    await session.execute(stmt)


@router.post("/manager")
async def alert_on_manager_removal(
    event: Event[UUID],
    mo: depends.GraphQLClient,
    email_client: depends.EmailClient,
    email_settings: depends.EmailSettings,
    settings: depends.Settings,
    session: depends.Session,
) -> None:
    """
    Listen to manager events and inform `datagruppen` when a manager leaves the
    company

    Developed for Silkeborg Kommune
    """
    uuid = event.subject
    logger.info("Listening on a manager event with uuid:", uuid=uuid)

    # Load manager data from MO
    manager = await get_manager_data(mo, uuid)
    if not manager:
        logger.info("Manager not found")
        return

    to_date = manager.validity.to
    employee_uuid = manager.employee_uuid
    org_unit_uuid = manager.org_unit_uuid

    if not to_date and employee_uuid:
        logger.info("Manager is currently employed. No message will be sent")
        return
    elif not to_date and not employee_uuid:  # branch for vacant manager object
        from_date = manager.validity.from_
        effective = from_date
        # Insert from_date in `to_datetime`, as a vacant from_date equals a terminated manager's to_date
        to_datetime = from_date.replace(tzinfo=None)
        template = load_template("alert_on_vacant_manager.html")
        logger.info("Vacant from (utc+0): ", datetime=to_datetime)
    else:  # branch for a manager object with an end date (possibly future)
        assert to_date is not None  # both branches above require `not to_date`
        effective = to_date
        # Format the to-date as a datetime object at UTC+0
        to_datetime = to_date.replace(tzinfo=None)
        template = load_template("alert_on_manager_termination.html")
        logger.info("Terminate from(utc+0): ", datetime=to_datetime)

    if settings.alert_manager_removal_exclude_org_units:
        ancestor_uuids = await get_org_unit_ancestor_uuids(mo, org_unit_uuid)
        excluded = ancestor_uuids & set(
            settings.alert_manager_removal_exclude_org_units
        )
        if excluded:
            logger.info(
                "Org unit or ancestor is excluded from manager removal alerts",
                excluded=excluded,
            )
            return

    defer_until_advance_notice(effective, settings)

    # Load employee data from MO
    if employee_uuid:
        employee = await get_employee_name(mo, employee_uuid)
    else:
        employee = EmployeeNameEmployeesObjectsCurrent.parse_obj(
            {"name": "Vacant manager"}
        )

    # Construct org unit location string
    org_unit = await get_org_unit_data(mo, org_unit_uuid)
    if not org_unit:
        logger.info(
            "Org unit is possibly terminated or doesn't exist. An email will not be sent"
        )
        return

    location = await get_org_unit_location(mo, org_unit_uuid)

    template_context = {
        "name": employee.name,
        "to_date": to_datetime.date(),
        "location": location,
        "user_key": org_unit.user_key,
    }

    if await _content_alert_already_sent(session, "manager", uuid, template_context):
        logger.info(
            "An identical alert has already been sent. An email will not be sent"
        )
        return

    message = template.render(context=template_context)

    if settings.alert_manager_removal_use_org_unit_emails:
        root = await get_org_unit_root(mo, org_unit_uuid)
        # if org_unit_uuid == root, we just use the address from the root
        if org_unit_uuid == root:
            receivers = await get_org_unit_address(mo, org_unit_uuid)
        else:
            receivers = await get_institution_address(mo, org_unit_uuid, root)
    else:
        receivers = set(email_settings.receivers)

    email_client.send_email(
        receivers,
        "En medarbejder er blevet fjernet fra lederfanen",
        message,
        "html",
    )
    await _record_content_alert(session, "manager", uuid, template_context)


async def _check_and_alert_org_unit_without_relation(
    uuid: UUID,
    mo: depends.GraphQLClient,
    email_client: EmailClient,
    settings: depends.Settings,
    email_settings: depends.EmailSettings,
    session: AsyncSession,
) -> None:
    """Check if an org unit in the Lønorganisation lacks a relation to
    an Administrationsorganisation unit, and send an alert email if so."""
    log = logger.bind(uuid=str(uuid))

    assert settings.root_loen_org
    root = settings.root_loen_org

    org_unit_data = await get_org_unit_relations(mo, org_unit_uuid=uuid)

    if not org_unit_data:
        log.info("Org unit not found")
        return

    # Ancestors are already fetched here, so apply the rule directly rather than
    # get_org_unit_root (which would re-query ancestors per unit).
    current = one(org_unit_data).current
    if root_uuid(uuid, current.ancestors) != root:
        log.info("Org unit is not in the Lønorganisation")
        return

    if current.related_units:
        for relation in current.related_units:
            for org_unit in relation.org_units:
                if root_uuid(org_unit.uuid, org_unit.ancestors) != root:
                    log.info("Org unit has a relation outside of the Lønorganisation")
                    # Clear any previous alert so a future removal re-alerts.
                    await session.execute(
                        delete(SentAlert).where(
                            SentAlert.alert_type == "relation",
                            SentAlert.object_uuid == uuid,
                        )
                    )
                    return

    existing = await session.scalar(
        select(SentAlert).where(
            SentAlert.alert_type == "relation",
            SentAlert.object_uuid == uuid,
        )
    )
    if existing:
        log.info("Alert already sent for this org unit. An email will not be sent")
        return

    # TODO: Change this logic, but for now reuse the config
    if settings.alert_manager_removal_use_org_unit_emails:
        if uuid == root:
            emails = await get_org_unit_address(mo, uuid)
        else:
            emails = await get_institution_address(mo, uuid, root)
    else:
        emails = set(email_settings.receivers)

    email_client.send_email(
        receiver=emails,
        subject="Manglende relation i Lønorganisation",
        body=(
            "Denne besked er sendt som en påmindelse om at "
            f"enheden: {current.name} "
            "ikke er relateret til en enhed i Administrationsorganisationen."
        ),
        texttype="plain",
    )
    session.add(SentAlert(alert_type="relation", object_uuid=uuid))


@router.post("/org_unit")
async def handle_org_unit(
    event: Event[UUID],
    mo: depends.GraphQLClient,
    email_client: depends.EmailClient,
    settings: depends.Settings,
    email_settings: depends.EmailSettings,
    session: depends.Session,
) -> None:
    uuid = event.subject
    logger.info("Obtained message", uuid=str(uuid))
    await _check_and_alert_org_unit_without_relation(
        uuid, mo, email_client, settings, email_settings, session
    )


@router.post("/related_unit")
async def handle_related_units(
    event: Event[UUID],
    mo: depends.GraphQLClient,
    email_client: depends.EmailClient,
    settings: depends.Settings,
    email_settings: depends.EmailSettings,
    session: depends.Session,
) -> None:
    """When a related_units object changes, check each lønorg unit involved
    to see if it still has a relation to an adm org.

    We use registrations (bitemporal history) because a deleted relation
    no longer has a current state — querying current would return nothing.
    Registrations let us find which org units were involved historically."""
    uuid = event.subject
    log = logger.bind(uuid=str(uuid))
    log.info("Obtained related_units message")

    related_units = await get_related_units_data(mo, related_units_uuid=uuid)

    if not related_units:
        log.info("Related units not found")
        return

    # Collect all unique org unit UUIDs across all registrations and
    # validity periods. We use obj.uuid (always exists on the response)
    # rather than obj.current.uuid, since current can be None for
    # terminated or future-dated org units.
    # The root/lønorg check is handled by _check_and_alert_org_unit_without_relation.
    org_unit_uuids: set[UUID] = set()
    for related_unit in related_units:
        for registration in related_unit.registrations:
            for validity in registration.validities:
                for obj in validity.org_units_response.objects:
                    org_unit_uuids.add(obj.uuid)

    for org_unit_uuid in org_unit_uuids:
        await _check_and_alert_org_unit_without_relation(
            org_unit_uuid, mo, email_client, settings, email_settings, session
        )


@router.post("/rolebinding")
async def alert_on_rolebinding(
    event: Event[UUID],
    mo: depends.GraphQLClient,
    email_client: depends.EmailClient,
    email_settings: depends.EmailSettings,
    settings: depends.Settings,
    session: depends.Session,
) -> None:
    uuid = event.subject
    ituser_uuid = await get_ituser_uuid_by_rolebinding(mo, uuid=uuid)
    if not ituser_uuid:
        logger.info(
            "IT-user is possibly terminated or doesn't exist. An email will not be sent"
        )
        return None
    return await generate_ituser_email(
        ituser_uuid, mo, email_client, email_settings, settings, session
    )


@router.post("/ituser")
async def alert_on_ituser(
    event: Event[UUID],
    mo: depends.GraphQLClient,
    email_client: depends.EmailClient,
    email_settings: depends.EmailSettings,
    settings: depends.Settings,
    session: depends.Session,
) -> None:
    return await generate_ituser_email(
        event.subject, mo, email_client, email_settings, settings, session
    )


async def generate_ituser_email(
    ituser_uuid: UUID,
    mo: depends.GraphQLClient,
    email_client: EmailClient,
    email_settings: depends.EmailSettings,
    settings: depends.Settings,
    session: AsyncSession,
) -> None:
    # Read all validities (not just `current`) so a terminated IT-user is
    # still visible.
    chosen: ItuserValiditiesItusersObjectsValidities | None = (
        extract_current_or_latest_validity(
            await get_ituser_validities(mo, uuid=ituser_uuid)
        )
    )
    if chosen is None:
        logger.info("IT-user doesn't exist. An email will not be sent")
        return

    if not chosen.person:
        logger.info("IT-user has no person. An email will not be sent")
        return

    if chosen.user_key == "nanoq-brugernavn":
        logger.info(
            "IT-user has default user_key 'nanoq-brugernavn'. An email will not be sent"
        )
        return

    defer_until_advance_notice(chosen.validity.from_, settings)

    # Terminated when the chosen validity has already ended; a future end
    # date still reads as active.
    now = datetime.datetime.now(datetime.UTC)
    to = chosen.validity.to
    to_date = to.date() if (to is not None and to <= now) else None
    terminated = to_date is not None

    person = one(chosen.person).name
    roles = [one(rb.role) for rb in chosen.rolebindings]

    template_context = {
        "person": person,
        "ituser": chosen.user_key,
        "itsystem": chosen.itsystem.name,
        "roles": roles,
        "terminated": terminated,
        "to_date": to_date,
    }

    # Dedup on sorted role names plus the termination date, so a termination
    # re-alerts instead of deduping against the creation.
    dedup_content = {
        "person": person,
        "ituser": chosen.user_key,
        "itsystem": chosen.itsystem.name,
        "roles": sorted(r.name for r in roles),
        "to_date": str(to_date),
    }

    if await _content_alert_already_sent(session, "ituser", ituser_uuid, dedup_content):
        logger.info(
            "An identical alert has already been sent. An email will not be sent"
        )
        return

    message = load_template("alert_on_rolebinding.html").render(
        context=template_context
    )
    subject = (
        "En IT-bruger er blevet nedlagt i MO"
        if terminated
        else "En IT-bruger er blevet oprettet i MO"
    )
    email_client.send_email(set(email_settings.receivers), subject, message, "html")
    await _record_content_alert(session, "ituser", ituser_uuid, dedup_content)
