# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from typing import Any
from uuid import UUID
import structlog

from more_itertools import one

from .helpers import extract_current_or_latest_validity

from .autogenerated_graphql_client.client import GraphQLClient
from .autogenerated_graphql_client.ituser_validities import (
    ItuserValiditiesItusersObjectsValidities,
)
from .autogenerated_graphql_client.manager_data import (
    ManagerDataManagersObjectsValidities,
)
from .autogenerated_graphql_client.org_unit_validities import (
    OrgUnitValiditiesOrgUnitsObjectsValidities,
)

logger = structlog.get_logger()


async def get_manager_data(
    mo: GraphQLClient, uuid: UUID
) -> ManagerDataManagersObjectsValidities | None:
    gql_response = await mo.manager_data(uuid)
    if gql_response.objects:
        return extract_current_or_latest_validity(one(gql_response.objects).validities)
    return None


async def get_employee_name(mo: GraphQLClient, uuid: UUID) -> Any:
    """
    Loads a user's name

    Args:
        uuid: List of user UUIDs to query
        graphql_session: The GraphQL session to run queries on

    Return:
        Dictionary with queried user data
    """
    gql_response = await mo.employee_name(uuid)
    return one(gql_response.objects).current


async def get_org_unit_data(mo: GraphQLClient, uuid: UUID) -> Any:
    """
    Loads a user's data

    Args:
        key: User UUID
        graphql_session: The GraphQL session to run queries on

    Return:
        Dictionary with queried org unit data
    """
    gql_response = await mo.org_unit_data(uuid)
    if not gql_response.objects:
        return None
    return one(gql_response.objects).current


async def get_org_unit_location(mo: GraphQLClient, uuid: UUID):
    """
    Constructs and org-unit location string, where different org-units in the
    hierarchy are separated by forward slashes.
    """
    gql_response = await mo.org_unit_ancestors(uuid)
    org_units = gql_response.objects
    current = one(org_units).current

    org_unit_location = ""
    if current:
        ancestors = [ancestor.name for ancestor in reversed(current.ancestors)]
        org_unit_location = " / ".join(ancestors + [current.name])

    return org_unit_location


def root_uuid(uuid: UUID, ancestors: list) -> UUID:
    """An org unit's root: its top-most ancestor, or itself if it has none.

    Derived from `ancestors` because MO's `root` field materialises unreliably.
    Ancestors are nearest-first, so the last one is the root.
    """
    return ancestors[-1].uuid if ancestors else uuid


async def get_org_unit_root(mo: GraphQLClient, uuid: UUID) -> UUID:
    """Fetch an org unit's ancestors and return its root (see `root_uuid`)."""
    gql_response = await mo.org_unit_ancestors(uuid)
    current = one(gql_response.objects).current
    return root_uuid(uuid, current.ancestors if current else [])


async def get_org_unit_ancestor_uuids(mo: GraphQLClient, uuid: UUID) -> set[UUID]:
    """The org unit's own UUID plus all its ancestor UUIDs.

    Empty if the org unit has no current state — it doesn't exist, or is
    terminated — since MO's current query returns no objects for
    it.
    """
    gql_response = await mo.org_unit_ancestors(uuid)
    if not gql_response.objects:
        return set()
    current = one(gql_response.objects).current
    ancestors = {ancestor.uuid for ancestor in current.ancestors} if current else set()
    return {uuid} | ancestors


async def get_org_unit_relations(mo: GraphQLClient, org_unit_uuid: UUID):
    gql_response = await mo.org_unit_relations(org_unit_uuid)
    return gql_response.objects


async def get_org_unit_validities(
    mo: GraphQLClient, uuid: UUID
) -> list[OrgUnitValiditiesOrgUnitsObjectsValidities]:
    """All of an org unit's validities across time (empty if it doesn't exist)."""
    gql_response = await mo.org_unit_validities(uuid)
    if not gql_response.objects:
        return []
    return one(gql_response.objects).validities


async def get_institution_address(mo: GraphQLClient, uuid: UUID, root: UUID):
    gql_response = await mo.institution_address(uuid, root)
    current = one(gql_response.objects).current
    addresses = {address.value for address in current.addresses} if current else set()

    return addresses


async def get_org_unit_address(mo: GraphQLClient, uuid: UUID):
    gql_response = await mo.org_unit_address(uuid)
    current = one(gql_response.objects).current
    addresses = {address.value for address in current.addresses} if current else set()

    return addresses


async def get_related_units_data(mo: GraphQLClient, related_units_uuid: UUID):
    _response = await mo.related_unit_registrations(related_units_uuid)
    return _response.objects


async def get_ituser_uuid_by_rolebinding(mo: GraphQLClient, uuid: UUID) -> UUID | None:
    try:
        gql_response = await mo.rolebinding(uuid)
        current = one(gql_response.objects).current
        if current is None:
            return None
        return one(current.ituser).uuid
    except Exception:
        logger.warning(
            "Failed to fetch ituser from rolebinding UUID. "
            "This is usually caused by rolebinding events being fired, when it should've only been an ituser event"
        )
        return None


async def get_ituser_validities(
    mo: GraphQLClient, uuid: UUID
) -> list[ItuserValiditiesItusersObjectsValidities]:
    """All of an IT-user's validities across time (empty if it doesn't exist)."""
    gql_response = await mo.ituser_validities(uuid)
    if not gql_response.objects:
        return []
    return one(gql_response.objects).validities
