# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""Notification queue: events enqueue objects here, and a scheduled sweep
evaluates each object's settled state once — so a burst of events for the same
object results in at most one email."""

import asyncio
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from contextlib import suppress
from datetime import datetime
from uuid import UUID

import structlog
from cronsim import CronSim
from fastramqpi.context import Context
from sqlalchemy import delete
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import async_sessionmaker

from .autogenerated_graphql_client import GraphQLClient
from .config import EmailSettings
from .mail import EmailClient
from .models import PendingNotification

logger = structlog.get_logger()


async def enqueue(session: AsyncSession, alert_type: str, object_uuid: UUID) -> None:
    """Record that an object needs evaluating when the queue is processed.

    Idempotent: repeated events for the same object coalesce into one row.
    """
    stmt = (
        pg_insert(PendingNotification)
        .values(alert_type=alert_type, object_uuid=object_uuid)
        .on_conflict_do_nothing(index_elements=["alert_type", "object_uuid"])
    )
    await session.execute(stmt)
    logger.info("Notification queued", alert_type=alert_type, uuid=object_uuid)


async def process_pending(
    sessionmaker: async_sessionmaker,
    mo: GraphQLClient,
    email_client: EmailClient,
    email_settings: EmailSettings,
) -> dict[str, int]:
    """Evaluate every queued object and send whatever its settled state calls for.

    Each row is processed in its own transaction and deleted only on success,
    so failures stay queued and are retried on the next run.
    """
    # Imported here because agents.py imports enqueue from this module.
    from .agents import QUEUE_PROCESSORS

    async with sessionmaker() as session:
        rows = (await session.scalars(select(PendingNotification))).all()

    processed = failed = 0
    for row in rows:
        try:
            async with sessionmaker() as session, session.begin():
                await QUEUE_PROCESSORS[row.alert_type](
                    row.object_uuid, mo, email_client, email_settings, session
                )
                await session.execute(
                    delete(PendingNotification).where(PendingNotification.id == row.id)
                )
            processed += 1
        except Exception:
            failed += 1
            logger.exception(
                "Failed to process queued notification",
                alert_type=row.alert_type,
                uuid=row.object_uuid,
            )
    logger.info("Notification queue processed", processed=processed, failed=failed)
    return {"processed": processed, "failed": failed}


async def _scheduler_loop(context: Context) -> None:
    settings = context["user_context"]["settings"]
    while True:
        now = datetime.now()
        next_run = next(CronSim(settings.notification_send_schedule, now))
        logger.info("Notification queue: next scheduled run", at=next_run)
        await asyncio.sleep((next_run - now).total_seconds())
        try:
            # Resolved per run: the context is only fully populated once every
            # lifespan manager has started.
            await process_pending(
                sessionmaker=context["sessionmaker"],
                mo=context["graphql_client"],
                email_client=context["user_context"]["email_client"],
                email_settings=context["user_context"]["email_settings"],
            )
        except Exception:
            logger.exception("Notification queue run failed")


@asynccontextmanager
async def scheduler(context: Context) -> AsyncIterator[None]:
    """Lifespan manager running the queue schedule as a background task."""
    task = asyncio.create_task(_scheduler_loop(context))
    yield
    task.cancel()
    with suppress(asyncio.CancelledError):
        await task
