from typing import Any

import structlog
from fastapi import APIRouter
from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.main import FastRAMQPI

from .agents import router as event_router
from .autogenerated_graphql_client import GraphQLClient
from .config import EmailSettings
from .config import Settings
from .mail import EmailClient

logger = structlog.get_logger()
fastapi_router = APIRouter()

GRAPHQL_VERSION = 28


def create_fastramqpi(**kwargs: Any) -> FastRAMQPI:
    """
    Initiate a FastRAMQPI instance.
    """

    logger.info("Import settings")
    settings = Settings(**kwargs)
    email_settings = EmailSettings(**kwargs)

    # One listener per enabled event type. Listed explicitly so each
    # enable_*_events setting can be found by searching the code.
    listeners = []
    if settings.enable_address_events:
        listeners.append(
            Listener(
                namespace="mo",
                user_key="address",
                routing_key="address",
                path="/address",
            )
        )
    if settings.enable_manager_events:
        listeners.append(
            Listener(
                namespace="mo",
                user_key="manager",
                routing_key="manager",
                path="/manager",
            )
        )
    if settings.enable_rolebinding_events:
        listeners.append(
            Listener(
                namespace="mo",
                user_key="rolebinding",
                routing_key="rolebinding",
                path="/rolebinding",
            )
        )
    if settings.enable_ituser_events:
        listeners.append(
            Listener(
                namespace="mo",
                user_key="ituser",
                routing_key="ituser",
                path="/ituser",
            )
        )
    if settings.enable_org_unit_events:
        listeners.append(
            Listener(
                namespace="mo",
                user_key="org_unit",
                routing_key="org_unit",
                path="/org_unit",
            )
        )
    if settings.enable_related_unit_events:
        listeners.append(
            Listener(
                namespace="mo",
                user_key="related_unit",
                routing_key="related_unit",
                path="/related_unit",
            )
        )

    logger.info("FastRAMQPI setup")
    fastramqpi = FastRAMQPI(
        application_name=settings.application_name,
        settings=settings.fastramqpi,
        graphql_version=GRAPHQL_VERSION,
        graphql_client_cls=GraphQLClient,  # type: ignore
        graphql_events=GraphQLEvents(declare_listeners=listeners),
    )
    fastramqpi.add_context(settings=settings)
    fastramqpi.add_context(email_settings=email_settings)

    logger.info("Initializing email client")
    email_client = EmailClient(fastramqpi.get_context())

    email_client.check_connectivity()
    fastramqpi.add_context(email_client=email_client)

    app = fastramqpi.get_app()
    app.include_router(fastapi_router)
    app.include_router(event_router)

    # Handle bug in fastRAMQP
    # See https://git.magenta.dk/rammearkitektur/FastRAMQPI/-/merge_requests/91
    app.contact["email"] = "info@magenta.dk"  # type: ignore

    @app.post("/send_test_email", status_code=202, tags=["Test"])
    async def send_test_mail(receiver: str):
        """
        Send a test email using the settings in config.py
        """
        email_client.send_email(
            receiver={receiver},
            subject="Test mail from OS2MO-smtp agent",
            body="If you see this mail, the test has succeeded",
            texttype="plain",
            allow_receiver_override=False,
        )

    return fastramqpi


def create_app(fastramqpi: FastRAMQPI | None = None, **kwargs: Any) -> FastAPI:
    if fastramqpi is None:
        fastramqpi = create_fastramqpi(**kwargs)
    return fastramqpi.get_app()
